baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Geckoinfo.Top'
theme: 'hiruko'

params:
  paginate: 10
  RegularPages: 5
  NavItems: 
    -
      - "HOME"
      - "/"
      - "_blank"
      
    -
      - "POSTS"
      - "/"
      - "_blank"
     
    -
      - "ABOUT"
      - "/"
      - "_blank"
      

  CDN:
    Bootstrap:
      Version: "3.3.7"
      Path: "https://cdn.staticfile.org"
    FontAwesome:
      Version: "4.7.0"
      Path: "https://cdn.staticfile.org"
    JQuery:
      Version: "3.2.1"
      Path: "https://cdn.staticfile.org"
    MathJax:
      Version: "2.7.5"
      Path: "https://cdn.staticfile.org"
    Pangu:
      Version: "3.3.0"
      Path: "https://cdnjs.cloudflare.com/ajax/libs/"